name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
 - type: dropdown
    id: version
    attributes:
      label: Ventoy Version
      description: What version of ventoy are you running?
      options:
        - Latest relese (1.0.46)        
        - Old release
    validations:
      required: true
  - type: checkboxes
    id: latest_release
    attributes:
      label: Latest Release
      description: Have you tried with the latest release of Ventoy?
      options:
        - label: Yes. I have tried the latest release, but the bug still exist.
          required: false
        - label: No. I didn't try the latest release.
          required: false


  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
  - type: textarea
    id: Details about the bug.
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
